services:
  - type: web
    name: app-woyofall
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
